# Generated by Django 2.2.1 on 2020-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_portal', '0002_auto_20200723_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='rp',
            field=models.IntegerField(null=True),
        ),
    ]
