# Generated by Django 2.2.1 on 2020-07-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_portal', '0003_subcategory_rp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('WARNING', 'WARNING')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting_portal.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting_portal.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting_portal.Observation')),
            ],
        ),
    ]
