# Generated by Django 2.2.1 on 2020-07-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_portal', '0004_attachments_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='reported_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='reported_on',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('ALL', 'ALL'), ('ACTION_IN_PROGRESS', 'ACTION_IN_PROGRESS'), ('ACKNOWLEDGE_BY', 'ACKNOWLEDGE_BY'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED'), ('REPORTED', 'REPORTED')], default='REPORTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting_portal.Observation'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting_portal.Category'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting_portal.SubCategory'),
        ),
    ]
