# Generated by Django 2.2.1 on 2020-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_portal', '0007_auto_20200723_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='reported_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
