# Generated by Django 2.2.1 on 2020-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_portal', '0008_auto_20200724_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='due_date',
            field=models.DateTimeField(default='Not Set Due Date', null=True),
        ),
    ]
