# Generated by Django 2.2.1 on 2020-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_portal', '0009_auto_20200805_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
